language: ruby

before_install:
  - gem install bundler

services:
  - mongodb

rvm:
  - jruby-19mode

env:
  - "RAILS_VERSION=3.2"
  - "RAILS_VERSION=3.1"
  - "RAILS_VERSION=3.0"
  - "RAILS_VERSION=master"

matrix:
  allow_failures:
    - rvm: ruby-head
    - env: "RAILS_VERSION=master"
